(define (domain bloxorz)
  (:requirements :strips :typing)
  (:types tile dir)
  (:constants north east west south - dir)

  (:predicates
    (standing-on ?t - tile)
    (lying-on ?t - tile)
    (adjacent ?t1 - tile ?t2 - tile ?d - dir)
    (perpendicular ?d1 - dir ?d2 - dir)
    (active ?t - tile)
    (hard ?t - tile)
    (disabling ?t1 - tile ?t2 - tile)
    (enabling ?t1 - tile ?t2 - tile)
    (yellow ?t - tile)
  )

  (:action lay-down
    :parameters (?from - tile ?to1 - tile ?to2 - tile ?d - dir)
    :precondition (and
      (active ?to1) (active ?to2)
      (adjacent ?from ?to1 ?d) (adjacent ?to1 ?to2 ?d)
      (standing-on ?from)
    )
    :effect (and
      (not (standing-on ?from))
      (lying-on ?to2)
      (lying-on ?to1)
      (forall (?x - tile)
        (when (and (enabling ?to1 ?x) (not (active ?x)) (not (hard ?to1)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (enabling ?to2 ?x) (not (active ?x)) (not (hard ?to2)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (disabling ?to1 ?x) (active ?x) (not (hard ?to1)))
          (not (active ?x))))
      (forall (?x - tile)
        (when (and (disabling ?to2 ?x) (active ?x) (not (hard ?to2)))
          (not (active ?x))))
    )
  )

  (:action stand-up
    :parameters (?t1 - tile ?t2 - tile ?t3 - tile ?d - dir)
    :precondition (and
      (active ?t3)
      (lying-on ?t1) (lying-on ?t2)
      (adjacent ?t1 ?t2 ?d) (adjacent ?t2 ?t3 ?d)
      (not (yellow ?t3))
    )
    :effect (and
      (not (lying-on ?t1))
      (not (lying-on ?t2))
      (standing-on ?t3)
      (forall (?x - tile)
        (when (and (enabling ?t3 ?x) (not (active ?x)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (disabling ?t3 ?x) (active ?x))
          (not (active ?x))))

    )
  )

  (:action roll
    :parameters (?t1 - tile ?t2 - tile ?t3 - tile ?t4 - tile ?blockd - dir ?tod - dir)
    :precondition (and
      (perpendicular ?blockd ?tod)
      (active ?t3) (active ?t4)
      (lying-on ?t1) (lying-on ?t2)
      (adjacent ?t1 ?t2 ?blockd) (adjacent ?t3 ?t4 ?blockd)
      (adjacent ?t1 ?t3 ?tod) (adjacent ?t2 ?t4 ?tod)
    )
    :effect (and
      (not (lying-on ?t1))
      (not (lying-on ?t2))    
      (lying-on ?t3)
      (lying-on ?t4)
 
       (forall (?x - tile)
        (when (and (enabling ?t3 ?x) (not (active ?x)) (not (hard ?t3)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (enabling ?t4 ?x) (not (active ?x)) (not (hard ?t4)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (disabling ?t3 ?x) (active ?x) (not (hard ?t3)))
          (not (active ?x))))
      (forall (?x - tile)
        (when (and (disabling ?t4 ?x) (active ?x) (not (hard ?t4)))
          (not (active ?x))))
    )
  )
)