(define (domain bloxorz)
  (:requirements :strips :typing :conditional-effects :negative-preconditions)
  (:types tile block direction)
  (:constants north east west south - direction)

  (:predicates
    ; block stands upright on one tile
    (standing-on ?b - block ?t - tile)
     ; block lies flat on a tile (one of the two)               
    (lying-on ?b - block ?t - tile)
    ; direction of t2 from t1
    (adjacent ?t1 - tile ?t2 - tile ?d - direction)
    ; two directions are perpendicular
    (perpendicular ?d1 - direction ?d2 - direction)
    ; tile is active (can be used)
    (active ?t - tile)                               
    (hard ?t - tile)
    ; t1 disables t2 when block is on t1
    (disabling ?t1 - tile ?t2 - tile)                           
    ; t1 enables t2 when block is on t1
    (enabling ?t1 - tile ?t2 - tile)                             
    ; tile is yellow (can't be stood on upright)
    (yellow ?t - tile)
    ; A block exists on this tile                                                                      
    (occupied ?t - tile)                                                                                  
  )

  (:action lay-down
    :parameters (?b - block ?from - tile ?to1 - tile ?to2 - tile ?d - direction)
    :precondition (and
      (active ?to1)
      (active ?to2)
      (not (occupied ?to1))
      (not (occupied ?to2))
      (standing-on ?b ?from)
      (adjacent ?from ?to1 ?d)
      (adjacent ?to1 ?to2 ?d)
    )
    :effect (and
      (not (standing-on ?b ?from))
      (lying-on ?b ?to2)
      (lying-on ?b ?to1)
      (occupied ?to1)
      (occupied ?to2)
      (not (occupied ?from))
      (forall (?x - tile)
        (when (and (enabling ?to1 ?x) (not (active ?x)) (not (hard ?to1)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (enabling ?to2 ?x) (not (active ?x)) (not (hard ?to2)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (disabling ?to1 ?x) (active ?x) (not (hard ?to1)))
          (not (active ?x))))
      (forall (?x - tile)
        (when (and (disabling ?to2 ?x) (active ?x) (not (hard ?to2)))
          (not (active ?x))))
    )
  )

  (:action stand-up
    :parameters (?b - block ?t1 - tile ?t2 - tile ?t3 - tile ?d - direction)
    :precondition (and
      (active ?t3)
      (lying-on ?b ?t1)
      (lying-on ?b ?t2)
      (not (occupied ?t3))
      (adjacent ?t1 ?t2 ?d)
      (adjacent ?t2 ?t3 ?d)
      ; the tile we are going to stand on must not be yellow
      (not (yellow ?t3))
    )
    :effect (and
      (not (lying-on ?b ?t1))
      (not (lying-on ?b ?t2))
      (not (occupied ?t1))
      (not (occupied ?t2))
      (standing-on ?b ?t3)
      (occupied ?t3)
      (forall (?x - tile)
        (when (and (enabling ?t3 ?x) (not (active ?x)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (disabling ?t3 ?x) (active ?x))
          (not (active ?x))))

    )
  )

  (:action roll
    :parameters (?b - block ?t1 - tile ?t2 - tile ?t3 - tile ?t4 - tile ?blockd - direction ?tod - direction)
    :precondition (and
      (perpendicular ?blockd ?tod)
      (active ?t3)
      (active ?t4)
      (lying-on ?b ?t1)
      (lying-on ?b ?t2)
      (not (occupied ?t3))
      (not (occupied ?t4))
      (adjacent ?t1 ?t2 ?blockd)
      (adjacent ?t3 ?t4 ?blockd)
      (adjacent ?t1 ?t3 ?tod)
      (adjacent ?t2 ?t4 ?tod)
    )
    :effect (and
      (not (lying-on ?b ?t1))
      (not (lying-on ?b ?t2))    
      (lying-on ?b ?t3)
      (lying-on ?b ?t4)
      (occupied ?t3)
      (occupied ?t4)
      (not (occupied ?t1))
      (not (occupied ?t2))
      (forall (?x - tile)
        (when (and (enabling ?t3 ?x) (not (active ?x)) (not (hard ?t3)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (enabling ?t4 ?x) (not (active ?x)) (not (hard ?t4)))
          (active ?x)))
      (forall (?x - tile)
        (when (and (disabling ?t3 ?x) (active ?x) (not (hard ?t3)))
          (not (active ?x))))
      (forall (?x - tile)
        (when (and (disabling ?t4 ?x) (active ?x) (not (hard ?t4)))
          (not (active ?x))))
    )
  )
)